name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      — '*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        name: Set env
      -
        name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: registry.nonnoalex.dev/moralb/moralbwebsite
          tags: |
            type=raw,value=latest,enable=${{ endsWith(GitHub.ref, 'master') }}
            type=ref,event=tag
          flavor: |
            latest=false
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: registry.nonnoalex.dev
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
